translate initial text and first part of Database section
IuryAlves/system-design-primer pull request #30
Opened 2017-12-17 21:59 UTC by hilam

2017-12-20 19:44 UTC, IuryAlves requested changes

2017-12-20 19:44 UTC, IuryAlves commented on README-pt-BR.md
> +        * [Armazenamento Key-value](#key-value-store)
O termo `Chave-Valor` é bem comum em artigos e livros sobre banco de dados.

 O que acha de deixar em português ?

@hilam

2017-12-20 19:44 UTC, IuryAlves commented on README-pt-BR.md
> +Este tópico é melhor discutido na seção [Banco de dados](#database):
Não seria `#banco-de-dados` no lugar de `#database` ?

@hilam

2017-12-20 19:44 UTC, IuryAlves commented on README-pt-BR.md
> +* **Durabilidade** - Uma vez a transação sendo commitada (efetivada), será armazenada
Uma vez que a transação foi commitada (efetivada), ela continuará armazenada.

@hilam

2017-12-20 19:44 UTC, IuryAlves commented on README-pt-BR.md
> -* **Isolation** - Executing transactions concurrently has the same results as if the transactions were executed serially
Esse `ing` do `Executing` parece um gerúndio mas ele na verdade é um substantivo (no português).

A tradução seria `Executar`.

Referências: https://www.englishexperts.com.br/usos-da-terminacao-ing/

@hilam

2017-12-20 19:44 UTC, IuryAlves commented on README-pt-BR.md
> +* Veja [Desvantagem(ns): replicação](#desvantagemns-replicação) para pontosrelacionados a **ambos** master-slave e master-master.
Falta um espaço entre `pontos` e `relacionados`

@hilam

2017-12-22 22:16 UTC, hilam commented
Vou corrigir e atualizar a PR. Obrigado.


-------------------------------------
Hildeberto Abreu Magalhães
https://github.com/hilam
http://hilam.wordpress.com


2017-12-20 16:44 GMT-03:00 iury <notifications@github.com>:

> *@IuryAlves* requested changes on this pull request.
> ------------------------------
>
> In README-pt-BR.md
> <https://github.com/IuryAlves/system-design-primer/pull/30#discussion_r158112769>
> :
>
> >      * [NoSQL](#nosql)
> -        * [Key-value store](#key-value-store)
> -        * [Document store](#document-store)
> -        * [Wide column store](#wide-column-store)
> -        * [Graph Database](#graph-database)
> -    * [SQL or NoSQL](#sql-or-nosql)
> +        * [Armazenamento Key-value](#key-value-store)
>
> O termo Chave-Valor é bem comum em artigos e livros sobre banco de dados.
>
> O que acha de deixar em português ?
>
> @hilam <https://github.com/hilam>
> ------------------------------
>
> In README-pt-BR.md
> <https://github.com/IuryAlves/system-design-primer/pull/30#discussion_r158113384>
> :
>
> > @@ -510,7 +512,7 @@ Active-active failover can also be referred to as master-master failover.
>
>  #### Master-slave and master-master
>
> -This topic is further discussed in the [Database](#database) section:
> +Este tópico é melhor discutido na seção [Banco de dados](#database):
>
> Não seria #banco-de-dados no lugar de #database ?
>
> @hilam <https://github.com/hilam>
> ------------------------------
>
> In README-pt-BR.md
> <https://github.com/IuryAlves/system-design-primer/pull/30#discussion_r158115130>
> :
>
> >
> -* **Atomicity** - Each transaction is all or nothing
> -* **Consistency** - Any transaction will bring the database from one valid state to another
> -* **Isolation** - Executing transactions concurrently has the same results as if the transactions were executed serially
> -* **Durability** - Once a transaction has been committed, it will remain so
> +* **Atomicidade** - Cada transação é tudo ou nada
> +* **Consistência** - Qualquer transação levará o banco de dados de um estado válido para outro
> +* **Isolamento** - Executando transações concorrentemente obteremos os mesmos resultados como se as transações fossem executadas serialmente (em sequência)
> +* **Durabilidade** - Uma vez a transação sendo commitada (efetivada), será armazenada
>
> Uma vez que a transação foi commitada (efetivada), ela continuará
> armazenada.
>
> @hilam <https://github.com/hilam>
> ------------------------------
>
> In README-pt-BR.md
> <https://github.com/IuryAlves/system-design-primer/pull/30#discussion_r158116552>
> :
>
> >
> -* **Atomicity** - Each transaction is all or nothing
> -* **Consistency** - Any transaction will bring the database from one valid state to another
> -* **Isolation** - Executing transactions concurrently has the same results as if the transactions were executed serially
>
> Esse ing do Executing parece um gerúndio mas ele na verdade é um
> substantivo (no português).
>
> A tradução seria Executar.
>
> Referências: https://www.englishexperts.com.br/usos-da-terminacao-ing/
>
> @hilam <https://github.com/hilam>
> ------------------------------
>
> In README-pt-BR.md
> <https://github.com/IuryAlves/system-design-primer/pull/30#discussion_r158117372>
> :
>
> >
> -* You'll need a load balancer or you'll need to make changes to your application logic to determine where to write.
> -* Most master-master systems are either loosely consistent (violating ACID) or have increased write latency due to synchronization.
> -* Conflict resolution comes more into play as more write nodes are added and as latency increases.
> -* See [Disadvantage(s): replication](#disadvantages-replication) for points related to **both** master-slave and master-master.
> +* Será necessário um "balanceador de carga" ou fazer mudanças na lógica das aplicações para determinar onde escrever.
> +* Muitos sistemas master-master ou são fracamente consistentes (violando ACID) ou tem a latência de escrita aumentada, devido à sincronização.
> +* A necessidade de resolução de conflitos acontece mais vezes, quanto mais os nós de escrita são adicionados e a latência aumenta.
> +* Veja [Desvantagem(ns): replicação](#desvantagemns-replicação) para pontosrelacionados a **ambos** master-slave e master-master.
>
> Falta um espaço entre pontos e relacionados
>
> @hilam <https://github.com/hilam>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/IuryAlves/system-design-primer/pull/30#pullrequestreview-84870039>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA-Df7ZDH8ZAYHH580YFNLB4e9OdrUsOks5tCWO4gaJpZM4REz_i>
> .
>

2018-01-09 00:03 UTC, IuryAlves approved these changes
Obrigado @hilam e desculpa a demora em revisar. Estava de férias.

2018-01-09 00:03 UTC, merged